#
# mozaik generic demo dashboard
#
# It's not required, but you should add this env var,
# without it, you'll probably reach the API rate limit.
#
# GITHUB_API_TOKEN=xxxxx
#
port: 5000

# define duration between each dashboard rotation (ms)
rotationDuration: 10000
# define the interval used by Moza√Øk Bus to call registered APIs
apisPollInterval: 10 * 1000

dashboards:
- columns: 4
  rows:    2
  title:   Overwatch Dashboard
  widgets:
  - extension:    circle
    widget:       BuildStatuses
    name: noms-digital-studio
    repos:
        - noms-digital-studio/csra-app#master
        - noms-digital-studio/csra-mvp#master
        - noms-digital-studio/iis#master
        - noms-digital-studio/iis-feature-specs#master
    columns:      1
    rows:         1
    x:            0
    y:            0
